require('telescope').setup({})
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<Space><Space>', builtin.find_files, {})
vim.keymap.set('n', '<Space>fg', builtin.live_grep, {})
vim.keymap.set('n', '<Space>f', builtin.help_tags, {})
